# AI solving a puzzle 

## we are writing an algorithm to give birth to this AI, we will teach it how to solve puzzles using hints. And just like humans we will try to teach AI to learn information from the given problem, how to make smart choices.


## Phase 1

### Requirements : 
1. There's a puzzle board of m rows and n columns
2. There's going to be say a bag of pieces in the form of list given to the AI
3. We are going to give no/some inteligent information to the AI

example :
As an input we are going to give a shuffled list of pieces 

list_pieces = [4, 5, 1, 2, 3, 8, 9 , 6, 7]

size of list_pieces = m * n

This is how it looks after putting it together

| 1 | 2 | 3 |

| 4 | 5 | 6 |

| 7 | 8 | 9 |....[3 x 3]


### Rules
1. Sorting algorithms are strictly not allowed for directly placing pieces together
2. [A1] : only piece around neighbours can be added
3. 


### Additional info / heuristic function : 
Like humans we are going to teach the AI how to find information from whatever is the input 
1. is given piece a corner piece, edge piece
    -> we usually start or identify a piece as corner piece or an edge piece which helps us identify if



### Algorithm
1. takes hint and learns how to solve puzzle using BFS and DFS separately
 

## Phase 2

### Goals -  
- Instead of a numeric puzzle, use actual pictorial puzzle. 
- using image processing and recognition find neighbouring puzzle pieces to complete the puzzle  


In [1]:
from copy import deepcopy
import random

import numpy as np

from random import uniform
import time
from IPython.display import display, clear_output


# INPUTS

m x n puzzle

In [2]:
m = 4
n = 3

# Algorithm Phase 1

## Requirements gathering from input

In [3]:
elements = m*n
elements

12

In [4]:
pieces = [ x for x in range(1,elements+1)]
true_pieces = deepcopy(pieces)
true_pieces
pieces

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [5]:
# heuristic information : corner pieces
dict_corner_pieces = {}
corner_pieces = [ 1, n , elements, elements - (n-1)]

dict_corner_pieces[corner_pieces[0]] = 'TOP_LEFT'
dict_corner_pieces[corner_pieces[1]] = 'TOP_RIGHT'
dict_corner_pieces[corner_pieces[2]] = 'BOTTOM_RIGHT'
dict_corner_pieces[corner_pieces[3]] = 'BOTTOM_LEFT'

print(f'{corner_pieces=}')

h = {}
for piece in true_pieces:
    if dict_corner_pieces.get(piece)!=None :
        h[piece] = dict_corner_pieces.get(piece)
    else :
         h[piece] = dict_corner_pieces.get(piece)
            
# heuristic information : edge pieces

# find top edges | b/w corner_pieces
for top_edge_pieces in range(2,n):
    h[top_edge_pieces]='TOP'
#     print(top_edge_pieces)

# find right edges
for right_edge_pieces in range(2*n,elements,n):
    h[right_edge_pieces]='RIGHT'
#     print(right_edge_pieces)
    
# find bottom edges
for bottom_edge_pieces in range(corner_pieces[-1]+1,elements,1):
    h[bottom_edge_pieces]='BOTTOM'
#     print(bottom_edge_pieces)

# find left edges 
for left_edge_pieces in range(1+n,corner_pieces[3],n):
    h[left_edge_pieces]='LEFT'
#     print(left_edge_pieces)
    
h       

corner_pieces=[1, 3, 12, 10]


{1: 'TOP_LEFT',
 2: 'TOP',
 3: 'TOP_RIGHT',
 4: 'LEFT',
 5: None,
 6: 'RIGHT',
 7: 'LEFT',
 8: None,
 9: 'RIGHT',
 10: 'BOTTOM_LEFT',
 11: 'BOTTOM',
 12: 'BOTTOM_RIGHT'}

## Pre-requisites 

In [6]:
# check if goal reached
def goal_test(array_2d):
#     print(f'{len(array_2d)== elements}')
    return len(array_2d)== elements

In [7]:
# empty place to put in puzzle
# puzzle=None
puzzle = np.ndarray(shape=(m,n), dtype=float, order='F')
for _m in range(0,m):
    for _n in range(0,n):
        puzzle[_m][_n]=None

puzzle

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [8]:
# shuffle pieces
random.shuffle(pieces)
pieces

[4, 8, 9, 12, 7, 1, 3, 2, 10, 6, 11, 5]

In [9]:
neighbours_index = [-n , 1 , n , -1 ]
nrighbour_position = [ 'TOP', 'RIGHT', 'BOTTOM', 'LEFT']
positioning_map = { neighbour : position  for neighbour,
            position in zip(nrighbour_position , neighbours_index)} 

In [10]:


print(positioning_map)
def get_neighbours(piece : int):
    neighbours = [ x+piece for x in neighbours_index ]
    
    if ( h[piece] != None):
        if h[piece] == 'TOP_LEFT':
            neighbours[0] = None
            neighbours[-1] = None
        elif h[piece] == 'TOP':
            neighbours[0] = None
        elif h[piece] == 'TOP_RIGHT':
            neighbours[0] = None
            neighbours[1] = None
        elif h[piece] == 'RIGHT':
            neighbours[1] = None
        elif h[piece] == 'BOTTOM_RIGHT':
            neighbours[1] = None
            neighbours[2] = None
        elif h[piece] == 'BOTTOM':
            neighbours[2] = None
        elif h[piece] == 'BOTTOM_LEFT':
            neighbours[2] = None
            neighbours[-1] = None
        elif h[piece] == 'LEFT':
            neighbours[-1] = None
    
    new_dict = {position : neighbour  for neighbour,
            position in zip(neighbours,nrighbour_position )} 
    return new_dict
get_neighbours(2)

{'TOP': -3, 'RIGHT': 1, 'BOTTOM': 3, 'LEFT': -1}


{'TOP': None, 'RIGHT': 3, 'BOTTOM': 5, 'LEFT': 1}

In [11]:
def aleady_placed_or_in_queue(piece_to_place:list, pieces_placed : list, piece):
#     print(f'check if {piece} in lists')
    
    for l_pieces in piece_to_place:
        l_piece = l_pieces[0]
        if(l_piece==piece):
#             print(f'{l_piece=}=={piece=} is{True}')
            return True
        
    for l_pieces in pieces_placed:
        l_piece = l_pieces[0]
        if(l_piece==piece):
#             print(f'{l_piece=}=={piece=} is{True}')
            return True
        
#     print(f'{piece=} Not found ')
    return False

## solves using BFS search 

In [12]:
# pick a start node

current_node = true_pieces[0] # start node

pieces_placed = [] # closed list
piece_to_place = [ ( current_node , None, None ) ] # open list

print(f'{pieces_placed=}')
print(f'{piece_to_place=}')

puzzle[0][0] = current_node

itr =1
while goal_test(pieces_placed)==False:
    clear_output(wait=True)
#     display(f'')

#     display(f'\n{itr=}')
#     display(f'{pieces_placed=}')
#     display(f'{piece_to_place=}')

    current_node = piece_to_place[0]
    current_piece = int(current_node[0])
    parent = current_node[1]
    position_wrt_parent = current_node[2]
    
    # pieces placed
    if( parent ):
        # find location of parent
        # find location to place using position wrt parent
        for row in range(0,m):
            for column in range(0,n):
                if( puzzle[row][column] == parent ):
                    if position_wrt_parent == 'TOP':
                        puzzle[row-1][column] = current_piece
                    elif position_wrt_parent == 'RIGHT':
                        puzzle[row][column+1] = current_piece
                    elif position_wrt_parent == 'BOTTOM':
                        puzzle[row+1][column] = current_piece
                    elif position_wrt_parent == 'LEFT':
                        puzzle[row][column-1] = current_piece
    pieces_placed.append(current_node)
    display(puzzle)
    
    neighbours = get_neighbours(current_piece)
    for k,v in neighbours.items():
        if v : 
            neighbour = v
            if ( aleady_placed_or_in_queue(piece_to_place, pieces_placed,neighbour )==False ):
#                 print(f'adding {neighbour}')
                piece_to_place.append( (neighbour, current_piece , k) )
    
    piece_to_place.remove(current_node)
    itr+=1
    time.sleep(0.5)

# print(f'\n\n{pieces_placed=}')    

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

## solves using DFS search 

In [13]:
# empty place to put in puzzle
# puzzle=None
puzzle = np.ndarray(shape=(m,n), dtype=float, order='F')
for _m in range(0,m):
    for _n in range(0,n):
        puzzle[_m][_n]=None

puzzle

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [14]:
# pick a start node

current_node = true_pieces[0] # start node

pieces_placed = [] # closed list
piece_to_place = [ ( current_node , None, None ) ] # open list

print(f'{pieces_placed=}')
print(f'{piece_to_place=}')

puzzle[0][0] = current_node

itr =1
while goal_test(pieces_placed)==False:
    clear_output(wait=True)
#     display(f'')

#     display(f'\n{itr=}')
#     display(f'{pieces_placed=}')
#     display(f'{piece_to_place=}')

    current_node = piece_to_place.pop(0)
    current_piece = int(current_node[0])
    parent = current_node[1]
    position_wrt_parent = current_node[2]
    
    # pieces placed
    if( parent ):
        # find location of parent
        # find location to place using position wrt parent
        for row in range(0,m):
            for column in range(0,n):
                if( puzzle[row][column] == parent ):
                    if position_wrt_parent == 'TOP':
                        puzzle[row-1][column] = current_piece
                    elif position_wrt_parent == 'RIGHT':
                        puzzle[row][column+1] = current_piece
                    elif position_wrt_parent == 'BOTTOM':
                        puzzle[row+1][column] = current_piece
                    elif position_wrt_parent == 'LEFT':
                        puzzle[row][column-1] = current_piece
    pieces_placed.append(current_node)
    display(puzzle)
    
    neighbours = get_neighbours(current_piece)
    for k,v in neighbours.items():
        if v : 
            neighbour = v
            if ( aleady_placed_or_in_queue(piece_to_place, pieces_placed,neighbour )==False ):
#                 print(f'adding {neighbour}')
                piece_to_place.insert(0, (neighbour, current_piece , k) )
    
    itr+=1
    time.sleep(0.5)

# print(f'\n\n{pieces_placed=}')    

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])